package routes

import "github.com/gin-gonic/gin"

func SetupRoutes(r *gin.Engine) {

	auth := r.Group("/api/auth")
	auth.POST("/sign-in", SignIn)
	auth.POST("/sign-up", SignUp)

	me := r.Group("/api/me")
	me.GET("/", GetMyCredentials)
	me.PUT("/", UpdateMyCredentials)
	me.GET("/podcast-lists", GetMyPodcastLists)
	me.GET("/playlists", GetMyPlaylists)
	me.GET("/following")
	me.GET("/liked")
	me.GET("/podcast-lists/comments", GetPodcastListComments)
	me.GET("/podcasts/comments", GetPodcastComments)
	me.GET("/presigned-url/image", GetPresignedURLForImage)
	me.GET("/presigned-url/podcast", GetPresignedURLForPodcast)

	categories := r.Group("/api/categories")
	categories.GET("/", GetCategories)
	categories.GET("/:id", GetCategoryByID)
	categories.POST("/", CreateCategory)
	categories.PUT("/:id", UpdateCategory)
	categories.DELETE("/:id", DeleteCategory)
	categories.GET("/:id/podcast-lists", GetPodcastListsByCategoryID)

	podcastLists := r.Group("/api/podcast-lists")
	podcastLists.GET("/", GetPodcastLists)
	podcastLists.GET("/:id", GetPodcastListByID)
	podcastLists.POST("/", CreatePodcastList)
	podcastLists.PUT("/:id", UpdatePodcastList)
	podcastLists.DELETE("/:id", DeletePodcastList)
	podcastLists.GET("/:id/podcasts")
	podcastLists.GET("/:id/comments", GetPodcastListComments)
	podcastLists.POST("/:id/comments", CreatePodcastListComment)
	podcastLists.PUT("/:id/comments/:commentId", UpdatePodcastListComment)
	podcastLists.DELETE("/:id/comments/:commentID", DeletePodcastListComment)
	podcastLists.POST("/:id/follow")
	podcastLists.DELETE("/:id/unfollow")

	podcasts := r.Group("/api/podcasts")
	podcasts.GET("/", GetPodcasts)
	podcasts.GET("/:id", GetPodcastByID)
	podcasts.POST("/", CreatePodcast)
	podcasts.PUT("/:id", UpdatePodcast)
	podcasts.DELETE("/:id", DeletePodcast)
	podcasts.GET("/:id/comments", GetPodcastComments)
	podcasts.POST("/:id/comments", CreatePodcastComment)
	podcasts.PUT("/:id/comments/:commentId", UpdatePodcastComment)
	podcasts.DELETE("/:id/comments/:commentId", DeletePodcastComment)
	podcastLists.POST("/:id/like")
	podcastLists.DELETE("/:id/unlike")

	playlists := r.Group("/api/playlists")
	playlists.GET("/", GetPlaylists)
	playlists.GET("/:id", GetPlaylistByID)
	playlists.POST("/", CreatePlaylist)
	playlists.PUT("/:id", UpdatePlaylist)
	playlists.DELETE("/:id", DeletePlaylist)
	playlists.GET("/:id/podcasts", GetPodcastsByPlaylistID)
	playlists.GET("/:id/podcasts", GetPlaylistPodcasts)
	playlists.POST("/:id/podcasts/:podcastId", AddPodcastToPlaylist)
	playlists.DELETE("/:id/podcasts/:podcastId", RemovePodcastFromPlaylist)

	users := r.Group("/api/users")
	users.GET("/", GetUsers)
	users.GET("/:id", GetUserByID)
	users.POST("/", CreateUser)
	users.PUT("/:id", UpdateUser)
	users.DELETE("/:id", DeleteUser)

}
